/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IdRouteImport } from './routes/$id'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiSessionsIdRouteImport } from './routes/api/sessions.$id'

const IdRoute = IdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsIdRoute = ApiSessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSessionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/sessions/$id': typeof ApiSessionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/sessions/$id': typeof ApiSessionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/sessions/$id': typeof ApiSessionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$id' | '/api/sessions' | '/api/sessions/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$id' | '/api/sessions' | '/api/sessions/$id'
  id: '__root__' | '/' | '/$id' | '/api/sessions' | '/api/sessions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdRoute: typeof IdRoute
  ApiSessionsRoute: typeof ApiSessionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$id': {
      id: '/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$id': {
      id: '/api/sessions/$id'
      path: '/$id'
      fullPath: '/api/sessions/$id'
      preLoaderRoute: typeof ApiSessionsIdRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
  }
}

interface ApiSessionsRouteChildren {
  ApiSessionsIdRoute: typeof ApiSessionsIdRoute
}

const ApiSessionsRouteChildren: ApiSessionsRouteChildren = {
  ApiSessionsIdRoute: ApiSessionsIdRoute,
}

const ApiSessionsRouteWithChildren = ApiSessionsRoute._addFileChildren(
  ApiSessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdRoute: IdRoute,
  ApiSessionsRoute: ApiSessionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
